[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["cd backend && python -m pip install -r requirements_simple.txt"]

[start]
cmd = "cd backend && python -m uvicorn app.main_simple:app --host 0.0.0.0 --port $PORT"